interfaces:
  TenGigabitEthernet 1/1:
    managed: true
  TenGigabitEthernet 1/2:
    managed: true
  TenGigabitEthernet 1/3:
    managed: true
  TenGigabitEthernet 1/4:
    managed: true
  TenGigabitEthernet 1/5:
    managed: true
  TenGigabitEthernet 1/6:
    managed: true
  TenGigabitEthernet 1/7:
    managed: true
  TenGigabitEthernet 1/8:
    managed: true
  TenGigabitEthernet 1/9:
    managed: true
  TenGigabitEthernet 1/10:
    managed: true
  TenGigabitEthernet 1/11:
    description: "OCT4-7"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 3803
    tagged:
      - 920
      - 921
  TenGigabitEthernet 1/12:
    managed: true
  TenGigabitEthernet 1/13:
    description: "OCT4-5"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 208
    tagged:
      - 213
      - 250
      - 351:499
      - 520:622
      - 623
      - 624:630
      - 911
      - 3801
  TenGigabitEthernet 1/14:
    description: "OCT4-4"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 208
    tagged:
      - 213
      - 250
      - 351:499
      - 520:622
      - 623
      - 624:630
      - 911
      - 3801
  TenGigabitEthernet 1/15:
    description: "OCT4-3"
    state: "up"
    mtu: 9216
    portmode: "access"
    untagged: 208
  TenGigabitEthernet 1/16:
    managed: true
  TenGigabitEthernet 1/17:
    description: "OCT4-1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 208
    tagged:
      - 213
      - 250
      - 351:499
      - 520:622
      - 623
      - 624:630
      - 911
      - 3801
  TenGigabitEthernet 1/18:
    description: "OCT4-0"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 207
      - 213
      - 911
  TenGigabitEthernet 1/19:
    state: "down"
  TenGigabitEthernet 1/20:
    description: "OCT4-0 2nd"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 208
    tagged:
      - 623
  TenGigabitEthernet 1/21:
    description: "OCT4-1 2nd"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 207
  TenGigabitEthernet 1/22:
    managed: true
  TenGigabitEthernet 1/23:
    state: "down"
  TenGigabitEthernet 1/24:
    description: "OCT4-4 2nd"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 207
  TenGigabitEthernet 1/25:
    description: "OCT4-5 2nd"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 207
  TenGigabitEthernet 1/26:
    state: "down"
  TenGigabitEthernet 1/27:
    state: "down"
  TenGigabitEthernet 1/28:
    state: "down"
  TenGigabitEthernet 1/29:
    state: "down"
  TenGigabitEthernet 1/30:
    state: "down"
  TenGigabitEthernet 1/31:
    state: "down"
  TenGigabitEthernet 1/32:
    state: "down"
  TenGigabitEthernet 1/33:
    # description: OCT4-CHA3-1A
    managed: true
  TenGigabitEthernet 1/34:
    # description: OCT4-CHA3-1B
    managed: true
  TenGigabitEthernet 1/35:
    # description: OCT4-CHA3-1C
    managed: true
  TenGigabitEthernet 1/36:
    # description: OCT4-CHA3-1D
    managed: true
  TenGigabitEthernet 1/37:
    # description: OCT4-CHA3-3A
    managed: true
  TenGigabitEthernet 1/38:
    # description: OCT4-CHA3-3B
    managed: true
  TenGigabitEthernet 1/39:
    # description: OCT4-CHA3-3C
    managed: true
  TenGigabitEthernet 1/40:
    # description: OCT4-CHA3-3D
    managed: true
  TenGigabitEthernet 1/41:
    # description: OCT4-CHA4-1A
    managed: true
  TenGigabitEthernet 1/42:
    # description: OCT4-CHA4-1B
    managed: true
  TenGigabitEthernet 1/43:
    # description: OCT4-CHA4-1C
    managed: true
  TenGigabitEthernet 1/44:
    # description: OCT4-CHA4-1D
    managed: true
  TenGigabitEthernet 1/45:
    # description: OCT4-CHA4-3A
    managed: true
  TenGigabitEthernet 1/46:
    # description: OCT4-CHA4-3B
    managed: true
  TenGigabitEthernet 1/47:
    # description: OCT4-CHA4-3C
    managed: true
  TenGigabitEthernet 1/48:
    # description: OCT4-CHA4-3D
    managed: true
  fortyGigE 1/49:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/49/1:
    #description: "OCT4-CHA1-01A"
    managed: true
  TenGigabitEthernet 1/49/2:
    #description: "OCT4-CHA1-01B"
    managed: true
  TenGigabitEthernet 1/49/3:
    #description: "OCT4-CHA1-01C"
    managed: true
  TenGigabitEthernet 1/49/4:
    #description: "OCT4-CHA1-01D"
    managed: true
  fortyGigE 1/50:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/50/1:
    #description: "OCT4-CHA1-03A"
    managed: true
  TenGigabitEthernet 1/50/2:
    #description: "OCT4-CHA1-03B"
    managed: true
  TenGigabitEthernet 1/50/3:
    #description: "OCT4-CHA1-03C"
    managed: true
  TenGigabitEthernet 1/50/4:
    #description: "OCT4-CHA1-03D"
    managed: true
  fortyGigE 1/51:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/51/1:
    #description: "OCT4-CHA2-01A"
    managed: true
  TenGigabitEthernet 1/51/2:
    #description: "OCT4-CHA2-01B"
    managed: true
  TenGigabitEthernet 1/51/3:
    #description: "OCT4-CHA2-01C"
    managed: true
  TenGigabitEthernet 1/51/4:
    #description: "OCT4-CHA2-01D"
    managed: true
  fortyGigE 1/52:
    fanout:
      type: "quad"
      speed: "10G"
  TenGigabitEthernet 1/52/1:
    #description: "OCT4-CHA2-03A"
    managed: true
  TenGigabitEthernet 1/52/2:
    #description: "OCT4-CHA2-03B"
    managed: true
  TenGigabitEthernet 1/52/3:
    #description: "OCT4-CHA2-03C"
    managed: true
  TenGigabitEthernet 1/52/4:
    #description: "OCT4-CHA2-03D"
    managed: true
  fortyGigE 1/53:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  fortyGigE 1/54:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  Port-channel 1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # CSAIL
      - 10
      # MOC Public IPs
      - 127
      # MOC
      - 204
      - 207
      - 208
      - 213
      - 250
      # ESI
      - 351:499
      - 520:622
      - 623
      - 624:630
      # MGMT
      - 911
      - 913
      # CloudLab Testing
      - 920
      - 921
      # CSAIL
      - 3801
      - 3802
      - 3803
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/53"
      - "fortyGigE 1/54"
  Vlan 207:
    state: "up"
    ip4: "10.1.0.14/24"
