interfaces:
  GigabitEthernet 1/1:
    description: "pc154-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/2:
    description: "pc155-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/3:
    description: "pc156-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/4:
    description: "pc157-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/5:
    description: "pc158-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/6:
    description: "pc159-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/7:
    description: "pc151-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/8:
    description: "pc153-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/9:
    description: "pc160-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/10:
    description: "pc161-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/11:
    description: "pc162-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/12:
    description: "pc163-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/13:
    description: "pc164-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/14:
    description: "pc165-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/15:
    description: "pc166-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/16:
    description: "pc167-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/17:
    description: "pc168-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/18:
    state: "down"
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    description: "pc154-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/26:
    description: "pc155-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/27:
    description: "pc156-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/28:
    description: "pc157-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/29:
    description: "pc158-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/30:
    description: "pc159-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/31:
    description: "pc151-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/32:
    description: "pc153-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/33:
    description: "pc160-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/34:
    description: "pc161-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/35:
    description: "pc162-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/36:
    description: "pc163-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/37:
    description: "pc164-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/38:
    description: "pc165-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/39:
    description: "pc166-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/40:
    description: "pc167-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/41:
    description: "pc168-ctrl"
    state: "up"
    portmode: "access"
    untagged: 84
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    state: "down"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    state: "down"
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    state: "down"
  TenGigabitEthernet 1/52:
    description: "OCT9-SW-TORS-A"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
      - 910
      - 930
  Vlan 930:
    state: "up"
    ip4: "10.80.2.93/20"
