interfaces:
  hundredGigE 1/1:
    description: "OCT9-FPGA3 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/2:
    description: "OCT9-FPGA3 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/3:
    description: "OCT9-FPGA4 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/4:
    description: "OCT9-FPGA4 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/5:
    description: "OCT9-FPGA5 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/6:
    description: "OCT9-FPGA5 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/7:
    description: "OCT9-FPGA6 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/8:
    description: "OCT9-FPGA6 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/9:
    description: "OCT9-FPGA7 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/10:
    description: "OCT9-FPGA7 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/11:
    description: "OCT9-FPGA8 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/12:
    description: "OCT9-FPGA8 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/13:
    description: "OCT9-FPGA1 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/14:
    description: "OCT9-FPGA1 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/15:
    description: "OCT9-FPGA2 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/16:
    description: "OCT9-FPGA2 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/17:
    state: "down"
  hundredGigE 1/18:
    state: "down"
  hundredGigE 1/19:
    state: "down"
  hundredGigE 1/20:
    state: "down"
  hundredGigE 1/21:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/21/1:
    description: "OCT9-FPGA2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/22:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/22/1:
    description: "OCT9-FPGA1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/23:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/23/1:
    description: "OCT9-FPGA8"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/24:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/24/1:
    description: "OCT9-FPGA7"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/25:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/25/1:
    description: "OCT9-FPGA6"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/26:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/26/1:
    description: "OCT9-FPGA5"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/27:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/27/1:
    description: "OCT9-FPGA4"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/28:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/28/1:
    description: "OCT9-FPGA3"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/29:
    state: "down"
  hundredGigE 1/30:
    state: "down"
  hundredGigE 1/31:
    state: "down"
  hundredGigE 1/32:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/33:
    description: "FPGA-BUILD1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/34:
    description: "OCT9-SW-HYB"
    state: "up"
    mtu: 9216
    portmode: "trunk"
    tagged:
      - 84
      - 910
      - 930
  Port-channel 1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
      - 910
      - 930
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/32"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.17/22"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.91/20"
