interfaces:
  GigabitEthernet 1/1:
    description: "OCT10-00 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/2:
    description: "OCT10-01 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/3:
    description: "OCT10-02 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/4:
    description: "OCT10-03 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/5:
    description: "OCT10-04 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/6:
    description: "OCT10-05 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/7:
    description: "OCT10-06 OBM"
    state: "up"
    portmode: "access"
    untagged: 912
    stp-edge: true
  GigabitEthernet 1/8:
    state: "down"
  GigabitEthernet 1/9:
    state: "down"
  GigabitEthernet 1/10:
    state: "down"
  GigabitEthernet 1/11:
    description: "ESI Undercloud Port 1"
    state: "up"
    portmode: "hybrid"
    untagged: 127
    tagged:
      - 207
      - 911
      - 912
    stp-edge: true
  GigabitEthernet 1/12:
    description: "ESI Undercloud Port 2"
    state: "up"
    portmode: "access"
    untagged: 214
    stp-edge: true
  GigabitEthernet 1/13:
    state: "down"
  GigabitEthernet 1/14:
    state: "down"
  GigabitEthernet 1/15:
    description: "AlanLiu-NetMon-OBM"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/16:
    state: "down"
  GigabitEthernet 1/17:
    description: "OCT-CORE-1 MGMT"
    state: "up"
    portmode: "access"
    untagged: 930
    stp-edge: true
  GigabitEthernet 1/18:
    description: "OCT-CORE-2 MGMT"
    state: "up"
    portmode: "access"
    untagged: 930
    stp-edge: true
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    description: "OCT-HEAD"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
      - 301
      - 910
      - 930
      - 931
      - 980
    stp-edge: true
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    description: "OCT-45 OBM"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/34:
    description: "OCT-43 OBM"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/35:
    description: "OCT-41 OBM"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    description: "#### Unknown Netgear"
    state: "up"
    portmode: "access"
    tagged:
      - 930
  GigabitEthernet 1/45:
    description: "OCT5-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 930
      - 931
    stp-edge: true
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    state: "down"
  TenGigabitEthernet 1/49:
    description: "MOC-MCORE-1 Port 49"
    state: "up"
  TenGigabitEthernet 1/50:
    description: "MOC-MCORE-1 Port 50"
    state: "up"
  TenGigabitEthernet 1/51:
    description: "OCT-CORE-1 Port 5/1"
    state: "up"
  TenGigabitEthernet 1/52:
    description: "OCT-CORE-2 Port 5/1"
    state: "up"
  Port-channel 10:
    description: "OCT-CORE-1 and OCT-CORE-2 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      # UMA Public IPs
      - 84
      # MOC
      - 127
      - 207
      - 214
      # Unity
      - 301
      # MGMT
      - 910
      - 911
      - 912
      - 930
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Port-channel 20:
    description: "MOC-MCORE-1 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 911
      - 930
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/49"
      - "TenGigabitEthernet 1/50"
  Vlan 930:
    state: "up"
    ip4: "10.80.1.11/20"
