interfaces:
  TenGigabitEthernet 1/1:
    description: "OCT2-U1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/2:
    description: "OCT2-U2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/3:
    description: "OCT2-U3"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/4:
    description: "OCT2-U4"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/5:
    description: "OCT2-U5"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/6:
    description: "OCT2-U6"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/7:
    description: "OCT2-U7"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/8:
    description: "OCT2-U8"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/9:
    description: "OCT2-U9"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/10:
    description: "OCT2-U10"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/11:
    description: "OCT2-U11"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/12:
    description: "OCT2-U12"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/13:
    description: "OCT2-U13"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/14:
    description: "OCT2-U14"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/15:
    description: "OCT2-U15"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/16:
    description: "OCT2-U16"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/17:
    description: "OCT2-U17"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/18:
    description: "OCT2-U18"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/19:
    description: "OCT2-U19"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/20:
    description: "OCT2-U20"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/21:
    description: "OCT2-U21"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/22:
    description: "OCT2-U22"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/23:
    description: "OCT2-U23"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/24:
    description: "OCT2-U24"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/25:
    description: "OCT2-U25"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/26:
    description: "OCT2-U26"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/27:
    description: "OCT2-U27"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/28:
    description: "OCT2-U28"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/29:
    description: "OCT2-U29"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/30:
    description: "OCT2-U30"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/31:
    description: "OCT2-U31"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/32:
    description: "OCT2-U32"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/33:
    description: "OCT2-U33"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/34:
    description: "OCT2-U34"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/35:
    description: "OCT2-U35"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/36:
    description: "OCT2-U36"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/37:
    description: "OCT2-U37"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/38:
    description: "OCT2-U38"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  TenGigabitEthernet 1/39:
    state: "down"
  TenGigabitEthernet 1/40:
    state: "down"
  TenGigabitEthernet 1/41:
    state: "down"
  TenGigabitEthernet 1/42:
    state: "down"
  TenGigabitEthernet 1/43:
    state: "down"
  TenGigabitEthernet 1/44:
    state: "down"
  TenGigabitEthernet 1/45:
    state: "down"
  TenGigabitEthernet 1/46:
    state: "down"
  TenGigabitEthernet 1/47:
    state: "down"
  TenGigabitEthernet 1/48:
    description: "OCT2-SW-CTRL"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
  fortyGigE 1/49:
    state: "down"
  fortyGigE 1/50:
    state: "down"
  fortyGigE 1/51:
    state: "down"
  fortyGigE 1/52:
    state: "down"
  fortyGigE 1/53:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  fortyGigE 1/54:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  Port-channel 1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 84
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "fortyGigE 1/53"
      - "fortyGigE 1/54"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.6/22"
