interfaces:
  hundredGigE 1/1:
    description: "OCT9-FPGA9 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/2:
    description: "OCT9-FPGA9 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/3:
    description: "OCT9-FPGA10 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/4:
    description: "OCT9-FPGA10 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/5:
    description: "OCT9-FPGA11 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/6:
    description: "OCT9-FPGA11 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/7:
    description: "OCT9-FPGA12 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/8:
    description: "OCT9-FPGA12 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/9:
    description: "OCT9-FPGA13 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/10:
    description: "OCT9-FPGA13 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/11:
    description: "OCT9-FPGA14 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/12:
    description: "OCT9-FPGA14 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/13:
    description: "OCT9-FPGA15 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/14:
    description: "OCT9-FPGA15 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/15:
    description: "OCT9-FPGA16 FPGA 1"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/16:
    description: "OCT9-FPGA16 FPGA 2"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
    fec: false
    autoneg: false
  hundredGigE 1/17:
    description: "OCT9-FPGA9 100G"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/18:
    description: "OCT9-FPGA10 100G"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/19:
    description: "OCT9-FPGA11 100G"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/20:
    description: "OCT9-FPGA12 100G"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/21:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/21/1:
    description: "OCT9-FPGA16"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/22:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/22/1:
    description: "OCT9-FPGA15"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/23:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/23/1:
    description: "OCT9-FPGA14"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/24:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/24/1:
    description: "OCT9-FPGA13"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/25:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/25/1:
    description: "OCT9-FPGA12"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/26:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/26/1:
    description: "OCT9-FPGA11"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/27:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/27/1:
    description: "OCT9-FPGA10"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/28:
    fanout:
      type: "single"
      speed: "40G"
  fortyGigE 1/28/1:
    description: "OCT9-FPGA9"
    state: "up"
    mtu: 9216
    portmode: "hybrid"
  hundredGigE 1/29:
    state: "down"
  hundredGigE 1/30:
    state: "down"
  hundredGigE 1/31:
    state: "down"
  hundredGigE 1/32:
    description: "OCT-CORE-3 Port #### Po1"
    state: "up"
    mtu: 9216
  TenGigabitEthernet 1/33:
    state: "down"
  TenGigabitEthernet 1/34:
    state: "down"
  Port-channel 1:
    description: "OCT-CORE-3 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 930
    mtu: 9216
    lacp-rate: "fast"
    lacp-members-active:
      - "hundredGigE 1/32"
  Vlan 910:
    state: "up"
    ip4: "10.0.0.20/22"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.92/20"
