interfaces:
  GigabitEthernet 1/1:
    description: "u38-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/2:
    description: "u37-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/3:
    description: "u36-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/4:
    description: "u35-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/5:
    description: "u34-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/6:
    description: "u33-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/7:
    description: "u32-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/8:
    description: "u31-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/9:
    description: "u30-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/10:
    description: "u29-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/11:
    description: "u28-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/12:
    description: "u27-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/13:
    description: "u26-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/14:
    description: "u25-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/15:
    description: "u24-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/16:
    description: "u23-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/17:
    description: "u22-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/18:
    description: "u21-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/19:
    description: "u20-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/20:
    description: "u19-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/21:
    description: "u18-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/22:
    description: "u17-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/23:
    description: "u16-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/24:
    description: "u15-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/25:
    description: "u14-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/26:
    description: "u13-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/27:
    description: "u12-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/28:
    description: "u11-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/29:
    description: "u10-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/30:
    description: "u9-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/31:
    description: "u8-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/32:
    description: "u7-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/33:
    description: "u6-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/34:
    description: "u5-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/35:
    description: "u4-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/36:
    description: "u3-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/37:
    description: "u2-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/38:
    description: "u1-ipmi"
    state: "up"
    portmode: "access"
    untagged: 910
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    state: "down"
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    description: "OCT2-SW-TORS Mgmt"
    state: "up"
    portmode: "access"
    untagged: 930
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    description: "OCT-MCORE-2"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 930
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    state: "down"
  TenGigabitEthernet 1/52:
    state: "down"
  Vlan 930:
    state: "up"
    ip4: "10.80.2.22/20"
