interfaces:
  GigabitEthernet 1/1:
    description: "U3-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/2:
    description: "U5-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/3:
    description: "U7-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/4:
    description: "U9-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/5:
    description: "U11-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/6:
    description: "U13-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/7:
    description: "U15-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/8:
    description: "U17-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/9:
    description: "U19-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/10:
    description: "U21-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/11:
    description: "U23-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/12:
    description: "U25-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/13:
    description: "U27-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/14:
    description: "U29-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/15:
    description: "U31-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/16:
    description: "U33-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/17:
    description: "U35-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/18:
    description: "U37-CMC"
    state: "up"
    portmode: "access"
    untagged: 911
    stp-edge: true
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    state: "down"
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    state: "down"
  GigabitEthernet 1/34:
    state: "down"
  GigabitEthernet 1/35:
    state: "down"
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    description: "MOC-R4PAC22-SW-TORS-A mgmt"
    state: "up"
    portmode: "access"
    untagged: 930
  GigabitEthernet 1/44:
    description: "MOC-R4PAC22-SW-TORS-B mgmt"
    state: "up"
    portmode: "access"
    untagged: 930
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    description: "MOC-MCORE-2 Uplink"
    state: "up"
    portmode: "trunk"
    tagged:
      - 911
      - 930
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    description: "Po1 Member MOC-R4PAC22-SW-TORS-A"
    state: "up"
  TenGigabitEthernet 1/52:
    description: "Po1 Member MOC-R4PAC22-SW-TORS-B"
    state: "up"
  Port-channel 1:
    description: "MOC-R4PAC22-SW-TORS LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 911
      - 930
    lacp-rate: "fast"
    interfaces:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Vlan 930:
    state: "up"
    ip4: "10.80.3.25/20"
