interfaces:
  GigabitEthernet 1/1:
    description: "####-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
      - 930
  GigabitEthernet 1/2:
    description: "####-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
      - 930
  GigabitEthernet 1/3:
    description: "####-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
      - 930
  GigabitEthernet 1/4:
    description: "####-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
      - 930
  GigabitEthernet 1/5:
    description: "####-SW-MGMT Link"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
      - 930
  GigabitEthernet 1/6:
    state: "down"
  GigabitEthernet 1/7:
    state: "down"
  GigabitEthernet 1/8:
    state: "down"
  GigabitEthernet 1/9:
    state: "down"
  GigabitEthernet 1/10:
    state: "down"
  GigabitEthernet 1/11:
    state: "down"
  GigabitEthernet 1/12:
    state: "down"
  GigabitEthernet 1/13:
    state: "down"
  GigabitEthernet 1/14:
    state: "down"
  GigabitEthernet 1/15:
    state: "down"
  GigabitEthernet 1/16:
    state: "down"
  GigabitEthernet 1/17:
    description: "OCT-CORE-3 MGMT"
    state: "up"
    portmode: "access"
    untagged: 930
    stp-edge: true
  GigabitEthernet 1/18:
    description: "OCT-CORE-4 MGMT"
    state: "up"
    portmode: "access"
    untagged: 930
    stp-edge: true
  GigabitEthernet 1/19:
    state: "down"
  GigabitEthernet 1/20:
    state: "down"
  GigabitEthernet 1/21:
    state: "down"
  GigabitEthernet 1/22:
    state: "down"
  GigabitEthernet 1/23:
    state: "down"
  GigabitEthernet 1/24:
    state: "down"
  GigabitEthernet 1/25:
    state: "down"
  GigabitEthernet 1/26:
    state: "down"
  GigabitEthernet 1/27:
    state: "down"
  GigabitEthernet 1/28:
    state: "down"
  GigabitEthernet 1/29:
    state: "down"
  GigabitEthernet 1/30:
    state: "down"
  GigabitEthernet 1/31:
    state: "down"
  GigabitEthernet 1/32:
    state: "down"
  GigabitEthernet 1/33:
    state: "down"
  GigabitEthernet 1/34:
    state: "down"
  GigabitEthernet 1/35:
    state: "down"
  GigabitEthernet 1/36:
    state: "down"
  GigabitEthernet 1/37:
    state: "down"
  GigabitEthernet 1/38:
    state: "down"
  GigabitEthernet 1/39:
    state: "down"
  GigabitEthernet 1/40:
    state: "down"
  GigabitEthernet 1/41:
    state: "down"
  GigabitEthernet 1/42:
    state: "down"
  GigabitEthernet 1/43:
    state: "down"
  GigabitEthernet 1/44:
    description: "#### Unknown Netgear"
    state: "up"
    portmode: "access"
    tagged:
      - 930
  GigabitEthernet 1/45:
    state: "down"
  GigabitEthernet 1/46:
    state: "down"
  GigabitEthernet 1/47:
    state: "down"
  GigabitEthernet 1/48:
    state: "down"
  TenGigabitEthernet 1/49:
    state: "down"
  TenGigabitEthernet 1/50:
    state: "down"
  TenGigabitEthernet 1/51:
    description: "OCT-CORE-3 Port 33"
    state: "up"
  TenGigabitEthernet 1/52:
    description: "OCT-CORE-4 Port 34"
    state: "up"
  Port-channel 10:
    description: "OCT-CORE-1 and OCT-CORE-2 LAG"
    state: "up"
    portmode: "trunk"
    tagged:
      - 910
      - 911
      - 912
      - 913
    lacp-rate: "fast"
    lacp-members-active:
      - "TenGigabitEthernet 1/51"
      - "TenGigabitEthernet 1/52"
  Vlan 930:
    state: "up"
    ip4: "10.80.1.12/20"
